const API_BASE = 'https://script.google.com/macros/s/AKfycbzYGQy2WXuETJrLgkoAOc2vphWW5IJZi7uacca7nUF-g13-a35MZiZclwrSgK1boyriZQ/exec';
let deferredPrompt = null;
let chartBar = null;
let chartLine = null;

const state = { boot:null, user:null, dashboard:null, items:[], stock:[], movs:[], units:[], suppliers:[], filters:{ item:'', categoria:'', estoque:'', mov:'', tipo:'' }, editingItem:null };
const views = { dashboard: q('dashboardView'), items: q('itemsView'), stock: q('stockView'), movs: q('movsView'), units: q('unitsView'), suppliers: q('suppliersView') };
function q(id){ return document.getElementById(id); }
function esc(v){ return String(v ?? '').replace(/[&<>\"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[s])) }
function num(v){ return Number(v||0) }
function fmt(v){ return num(v).toLocaleString('pt-BR') }
async function apiGet(params={}){ const url = new URL(API_BASE); Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v)); const r = await fetch(url); return r.json(); }
async function apiPost(body={}){ const r = await fetch(API_BASE,{ method:'POST', headers:{'Content-Type':'text/plain;charset=utf-8'}, body: JSON.stringify(body)}); return r.json(); }

async function bootstrap(){ const r = await apiGet({action:'bootstrap'}); if(r.ok){ state.boot=r; document.title=`Portal de Estoque - ${r.prefeitura}`; } }
async function login(){ const usuario=q('usuario').value.trim(), senha=q('senha').value; q('loginMsg').textContent='Entrando...'; const r = await apiGet({action:'login', usuario, senha}); if(!r.ok){ q('loginMsg').textContent=r.error||'Falha no login'; return; } state.user=r.user; sessionStorage.setItem('pmrg_user', JSON.stringify(r.user)); q('loginScreen').classList.add('hidden'); q('app').classList.remove('hidden'); q('userBox').innerHTML=`<strong>${esc(r.user.nome)}</strong><br><small>${esc(r.user.perfil)}</small>`; await loadAll(); switchView('dashboard'); }
async function loadAll(){ const [dash,items,stock,movs,units,suppliers] = await Promise.all([apiGet({action:'dashboard'}),apiGet({action:'items'}),apiGet({action:'stock'}),apiGet({action:'movs'}),apiGet({action:'units'}),apiGet({action:'suppliers'})]); state.dashboard=dash.data||{}; state.items=items.data||[]; state.stock=stock.data||[]; state.movs=movs.data||[]; state.units=units.data||[]; state.suppliers=suppliers.data||[]; renderDashboard(); renderItems(); renderStock(); renderMovs(); renderUnits(); renderSuppliers(); }
function switchView(view){ document.querySelectorAll('.view').forEach(v=>v.classList.remove('active')); document.querySelectorAll('.menu-btn').forEach(v=>v.classList.remove('active')); views[view].classList.add('active'); document.querySelector(`.menu-btn[data-view="${view}"]`)?.classList.add('active'); const meta={dashboard:['Dashboard','Visão geral do sistema'],items:['Itens','CRUD completo de materiais'],stock:['Estoque','Consulta consolidada com filtros'],movs:['Movimentações','Entradas e saídas com exclusão'],units:['Unidades','Consulta institucional'],suppliers:['Fornecedores','Consulta de fornecedores']}; q('pageTitle').textContent=meta[view][0]; q('pageSubtitle').textContent=meta[view][1]; if(window.innerWidth<=900) q('sidebar').classList.remove('open'); }

function renderDashboard(){ const d=state.dashboard||{}; views.dashboard.innerHTML=`<div class="cards"><div class="kpi"><div class="label">Total de itens</div><div class="value">${fmt(d.totalItens)}</div></div><div class="kpi"><div class="label">Estoque baixo</div><div class="value">${fmt(d.estoqueBaixo)}</div></div><div class="kpi"><div class="label">Validades próximas</div><div class="value">${fmt(d.validades)}</div></div><div class="kpi"><div class="label">Saldo total</div><div class="value">${fmt(d.saldoTotal)}</div></div></div><div class="layout-2"><div class="panel"><div class="toolbar"><h3>Itens por categoria</h3><span class="muted">Gráfico institucional</span></div><canvas id="barChart" height="140"></canvas></div><div class="panel"><div class="toolbar"><h3>Movimentação mensal</h3><span class="muted">Entradas e saídas</span></div><canvas id="lineChart" height="140"></canvas></div></div><div class="layout-2"><div class="panel"><div class="toolbar"><h3>Top 5 saldos</h3><span class="muted">Base consolidada</span></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>Item</th><th>Saldo</th><th>Status</th></tr></thead><tbody>${(d.topSaldo||[]).map(r=>`<tr><td>${esc(r.codigo)}</td><td>${esc(r.item)}</td><td>${fmt(r.saldo_atual)}</td><td><span class="badge ${r.status_estoque==='Baixo'?'low':'ok'}">${esc(r.status_estoque)}</span></td></tr>`).join('')}</tbody></table></div></div><div class="panel"><div class="toolbar"><h3>Movimentações recentes</h3><span class="muted">Últimos lançamentos</span></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Item</th><th>Tipo</th><th>Qtd</th></tr></thead><tbody>${(d.movimentacoesRecentes||[]).map(r=>`<tr><td>${esc(r.data)}</td><td>${esc(r.item)}</td><td>${esc(r.tipo)}</td><td>${fmt(r.quantidade)}</td></tr>`).join('')}</tbody></table></div></div></div>`; renderCharts(); }
function renderCharts(){ const d=state.dashboard||{}; const bar=q('barChart'); const line=q('lineChart'); if(!bar||!line||typeof Chart==='undefined') return; if(chartBar) chartBar.destroy(); if(chartLine) chartLine.destroy(); chartBar=new Chart(bar,{type:'bar',data:{labels:(d.porCategoria||[]).map(x=>x.categoria),datasets:[{label:'Itens',data:(d.porCategoria||[]).map(x=>x.total),backgroundColor:'#2e75b6'}]},options:{responsive:true,plugins:{legend:{display:false}}}}); chartLine=new Chart(line,{type:'line',data:{labels:(d.mensal||[]).map(x=>x.mes),datasets:[{label:'Entradas',data:(d.mensal||[]).map(x=>x.entrada),borderColor:'#2f855a',backgroundColor:'rgba(47,133,90,.15)',tension:.35},{label:'Saídas',data:(d.mensal||[]).map(x=>x.saida),borderColor:'#c53030',backgroundColor:'rgba(197,48,48,.15)',tension:.35}]},options:{responsive:true}}); }

function itemFormValues(){ return { codigo:q('f_codigo').value,item:q('f_item').value,categoria:q('f_categoria').value,unidade:q('f_unidade').value,qtd_minima:q('f_qmin').value,estoque_inicial:q('f_estini').value,fornecedor:q('f_fornecedor').value,local:q('f_local').value,classe:q('f_classe').value,uso_principal:q('f_uso').value,observacoes:q('f_obs').value,controla_lote:q('f_lote').value,controla_validade:q('f_validade').value,ativo:'SIM',usuario:state.user?.usuario||'web' }; }
function clearItemForm(){ ['f_codigo','f_item','f_categoria','f_unidade','f_qmin','f_estini','f_fornecedor','f_local','f_classe','f_uso','f_obs'].forEach(id=>q(id).value=''); q('f_lote').value='Não'; q('f_validade').value='Não'; state.editingItem=null; }
async function saveItem(){ const body=itemFormValues(); body.action = state.editingItem ? 'updateItem' : 'addItem'; const r = await apiPost(body); if(r.ok){ clearItemForm(); await loadAll(); switchView('items'); } }
function editItem(code){ const r=state.items.find(x=>String(x.codigo)===String(code)); if(!r) return; state.editingItem=code; q('f_codigo').value=r.codigo||''; q('f_item').value=r.item||''; q('f_categoria').value=r.categoria||''; q('f_unidade').value=r.unidade||''; q('f_qmin').value=r.qtd_minima||''; q('f_estini').value=r.estoque_inicial||''; q('f_fornecedor').value=r.fornecedor||''; q('f_local').value=r.local||''; q('f_classe').value=r.classe||''; q('f_uso').value=r.uso_principal||''; q('f_obs').value=r.observacoes||''; q('f_lote').value=r.controla_lote||'Não'; q('f_validade').value=r.controla_validade||'Não'; }
async function deleteItem(code){ if(!confirm('Excluir item '+code+'?')) return; const r=await apiPost({action:'deleteItem',codigo:code,usuario:state.user?.usuario||'web'}); if(r.ok) await loadAll(); }
function renderItems(){ const categorias=[...new Set(state.items.map(x=>x.categoria).filter(Boolean))].sort(); const list=state.items.filter(r=> (!state.filters.item || String(r.item).toLowerCase().includes(state.filters.item.toLowerCase()) || String(r.codigo).toLowerCase().includes(state.filters.item.toLowerCase())) && (!state.filters.categoria || String(r.categoria)===state.filters.categoria)); views.items.innerHTML=`<div class="panel"><div class="toolbar"><h3>Cadastro e edição de itens</h3><div class="toolbar-actions"><button class="primary-btn" onclick="saveItem()">${state.editingItem?'Atualizar item':'Salvar item'}</button><button class="ghost-btn" onclick="clearItemForm()">Limpar</button></div></div><div class="form-grid"><input id="f_codigo" placeholder="Código" /><input id="f_item" placeholder="Item" /><input id="f_categoria" placeholder="Categoria" /><input id="f_unidade" placeholder="Unidade" /><input id="f_qmin" type="number" placeholder="Quantidade mínima" /><input id="f_estini" type="number" placeholder="Estoque inicial" /><input id="f_fornecedor" placeholder="Fornecedor" /><input id="f_local" placeholder="Local" /><input id="f_classe" placeholder="Classe" /><input id="f_uso" placeholder="Uso principal" /><input id="f_obs" placeholder="Observações" /><select id="f_lote"><option>Não</option><option>Sim</option></select><select id="f_validade"><option>Não</option><option>Sim</option></select></div></div><div class="panel" style="margin-top:16px"><div class="toolbar"><h3>Itens cadastrados</h3><span class="muted">Total filtrado: ${list.length}</span></div><div class="filters"><input id="flt_item" placeholder="Buscar por código ou item" value="${esc(state.filters.item)}" oninput="state.filters.item=this.value; renderItems()" /><select id="flt_cat" onchange="state.filters.categoria=this.value; renderItems()"><option value="">Todas as categorias</option>${categorias.map(c=>`<option ${state.filters.categoria===c?'selected':''}>${esc(c)}</option>`).join('')}</select><div></div></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>Item</th><th>Categoria</th><th>Unidade</th><th>Fornecedor</th><th>Ações</th></tr></thead><tbody>${list.map(r=>`<tr><td>${esc(r.codigo)}</td><td>${esc(r.item)}</td><td>${esc(r.categoria)}</td><td>${esc(r.unidade)}</td><td>${esc(r.fornecedor)}</td><td><button class="ghost-btn" onclick="editItem('${esc(r.codigo)}')">Editar</button> <button class="danger-btn" onclick="deleteItem('${esc(r.codigo)}')">Excluir</button></td></tr>`).join('')}</tbody></table></div></div>`; if(state.editingItem){ setTimeout(()=>editItem(state.editingItem),0); } }

async function saveMovement(){ const body={ action:'addMovement', usuario:state.user?.usuario||'web', codigo:q('m_codigo').value, item:q('m_item').value, tipo:q('m_tipo').value, quantidade:q('m_quantidade').value, unidade:q('m_unidade').value, responsavel:q('m_responsavel').value, lote:q('m_lote').value, validade:q('m_validade').value, documento:q('m_doc').value, fornecedor:q('m_fornecedor').value, observacoes:q('m_obs').value }; const r=await apiPost(body); if(r.ok){ ['m_codigo','m_item','m_quantidade','m_unidade','m_responsavel','m_lote','m_validade','m_doc','m_fornecedor','m_obs'].forEach(id=>q(id).value=''); await loadAll(); switchView('movs'); } }
async function deleteMovement(id){ if(!confirm('Excluir movimentação '+id+'?')) return; const r=await apiPost({action:'deleteMovement',id,usuario:state.user?.usuario||'web'}); if(r.ok) await loadAll(); }
function renderMovs(){ const tipos=[...new Set(state.movs.map(x=>x.tipo).filter(Boolean))]; const list=state.movs.filter(r=>(!state.filters.mov || String(r.item).toLowerCase().includes(state.filters.mov.toLowerCase()) || String(r.codigo).toLowerCase().includes(state.filters.mov.toLowerCase())) && (!state.filters.tipo || String(r.tipo)===state.filters.tipo)); views.movs.innerHTML=`<div class="panel"><div class="toolbar"><h3>Nova movimentação</h3><div class="toolbar-actions"><button class="primary-btn" onclick="saveMovement()">Salvar movimentação</button></div></div><div class="form-grid"><input id="m_codigo" placeholder="Código" /><input id="m_item" placeholder="Item" /><select id="m_tipo"><option>Entrada</option><option>Saída</option></select><input id="m_quantidade" type="number" placeholder="Quantidade" /><input id="m_unidade" placeholder="Unidade" /><input id="m_responsavel" placeholder="Responsável" /><input id="m_lote" placeholder="Lote" /><input id="m_validade" type="date" placeholder="Validade" /><input id="m_doc" placeholder="Documento" /><input id="m_fornecedor" placeholder="Fornecedor" /><input id="m_obs" placeholder="Observações" /></div></div><div class="panel" style="margin-top:16px"><div class="toolbar"><h3>Histórico de movimentações</h3><span class="muted">Total filtrado: ${list.length}</span></div><div class="filters"><input placeholder="Buscar por item ou código" value="${esc(state.filters.mov)}" oninput="state.filters.mov=this.value; renderMovs()" /><select onchange="state.filters.tipo=this.value; renderMovs()"><option value="">Todos os tipos</option>${tipos.map(t=>`<option ${state.filters.tipo===t?'selected':''}>${esc(t)}</option>`).join('')}</select><div></div></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Data</th><th>Item</th><th>Tipo</th><th>Qtd</th><th>Unidade</th><th>Ações</th></tr></thead><tbody>${list.map(r=>`<tr><td>${esc(r.id)}</td><td>${esc(r.data)}</td><td>${esc(r.item)}</td><td>${esc(r.tipo)}</td><td>${fmt(r.quantidade)}</td><td>${esc(r.unidade)}</td><td><button class="danger-btn" onclick="deleteMovement('${esc(r.id)}')">Excluir</button></td></tr>`).join('')}</tbody></table></div></div>`; }

function renderStock(){ const cats=[...new Set(state.stock.map(x=>x.categoria).filter(Boolean))].sort(); const list=state.stock.filter(r=>(!state.filters.item || String(r.item).toLowerCase().includes(state.filters.item.toLowerCase()) || String(r.codigo).toLowerCase().includes(state.filters.item.toLowerCase())) && (!state.filters.categoria || String(r.categoria)===state.filters.categoria) && (!state.filters.estoque || String(r.status_estoque)===state.filters.estoque)); views.stock.innerHTML=`<div class="panel"><div class="toolbar"><h3>Estoque consolidado</h3><span class="muted">Total filtrado: ${list.length}</span></div><div class="filters"><input placeholder="Buscar por código ou item" value="${esc(state.filters.item)}" oninput="state.filters.item=this.value; renderStock()" /><select onchange="state.filters.categoria=this.value; renderStock()"><option value="">Todas as categorias</option>${cats.map(c=>`<option ${state.filters.categoria===c?'selected':''}>${esc(c)}</option>`).join('')}</select><select onchange="state.filters.estoque=this.value; renderStock()"><option value="">Todos os status</option><option ${state.filters.estoque==='OK'?'selected':''}>OK</option><option ${state.filters.estoque==='Baixo'?'selected':''}>Baixo</option></select></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>Item</th><th>Categoria</th><th>Saldo</th><th>Mínimo</th><th>Estoque</th><th>Validade</th></tr></thead><tbody>${list.map(r=>`<tr><td>${esc(r.codigo)}</td><td>${esc(r.item)}</td><td>${esc(r.categoria)}</td><td>${fmt(r.saldo_atual)}</td><td>${fmt(r.qtd_minima)}</td><td><span class="badge ${r.status_estoque==='Baixo'?'low':'ok'}">${esc(r.status_estoque)}</span></td><td><span class="badge ${r.status_validade==='Vencendo'?'low':r.status_validade==='Atenção'?'warn':'ok'}">${esc(r.status_validade)}</span></td></tr>`).join('')}</tbody></table></div></div>`; }
function renderUnits(){ views.units.innerHTML=`<div class="panel"><div class="toolbar"><h3>Unidades e setores</h3><span class="muted">Registros: ${state.units.length}</span></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>Unidade</th><th>Tipo</th><th>Região</th><th>Responsável</th></tr></thead><tbody>${state.units.map(r=>`<tr><td>${esc(r.codigo_unidade)}</td><td>${esc(r.unidade)}</td><td>${esc(r.tipo)}</td><td>${esc(r.regiao)}</td><td>${esc(r.responsavel)}</td></tr>`).join('')}</tbody></table></div></div>`; }
function renderSuppliers(){ views.suppliers.innerHTML=`<div class="panel"><div class="toolbar"><h3>Fornecedores</h3><span class="muted">Registros: ${state.suppliers.length}</span></div><div class="table-wrap"><table><thead><tr><th>Fornecedor</th><th>CNPJ</th><th>Cidade</th><th>UF</th></tr></thead><tbody>${state.suppliers.map(r=>`<tr><td>${esc(r.fornecedor)}</td><td>${esc(r.cnpj)}</td><td>${esc(r.cidade)}</td><td>${esc(r.uf)}</td></tr>`).join('')}</tbody></table></div></div>`; }

q('btnLogin').addEventListener('click', login); q('btnLogout').addEventListener('click', ()=>{ sessionStorage.removeItem('pmrg_user'); location.reload(); }); document.querySelectorAll('.menu-btn').forEach(btn=>btn.addEventListener('click', ()=>switchView(btn.dataset.view))); q('toggleSidebar').addEventListener('click', ()=>q('sidebar').classList.toggle('open')); q('btnSync').addEventListener('click', loadAll);
window.addEventListener('beforeinstallprompt', e=>{ e.preventDefault(); deferredPrompt=e; q('btnInstall').classList.remove('hidden'); }); q('btnInstall').addEventListener('click', async ()=>{ if(!deferredPrompt) return; deferredPrompt.prompt(); await deferredPrompt.userChoice; deferredPrompt=null; q('btnInstall').classList.add('hidden'); });
if('serviceWorker' in navigator){ window.addEventListener('load', ()=>navigator.serviceWorker.register('./sw.js')); }
bootstrap();
